import os
import sys
import glob
import pathlib
import setuptools


install_requires = []
tests_require = ["pytest", "pytest-cov", "pytest-flake8"]
dev_requires = install_requires + tests_require + ["documenteer[pipelines]"]
tools_path = pathlib.Path(setuptools.__path__[0])
base_prefix = pathlib.Path(sys.base_prefix)
data_files_path = tools_path.relative_to(base_prefix).parents[1]
policy_dir = [
    pp for pp in glob.glob("policy/**", recursive=True) if pathlib.Path(pp).is_dir()
]
policy_files = [
    (
        os.path.join(data_files_path, pd),
        [pf for pf in glob.glob(f"{pd}/*") if pathlib.Path(pf).is_file()],
    )
    for pd in policy_dir
]

scm_version_template = """# Generated by setuptools_scm
__all__ = ["__version__"]

__version__ = "{version}"
"""

setuptools.setup(
    name="ts_ofc",
    description="Optical Feedback Control ",
    use_scm_version={
        "write_to": "python/lsst/ts/ofc/version.py",
        "write_to_template": scm_version_template,
    },
    setup_requires=["setuptools_scm", "pytest-runner"],
    install_requires=install_requires,
    package_dir={"": "python"},
    packages=setuptools.find_namespace_packages(where="python"),
    data_files=policy_files,
    include_package_data=True,
    scripts=[],
    tests_require=tests_require,
    extras_require={"dev": dev_requires},
    license="GPL",
    project_urls={
        "Bug Tracker": "https://jira.lsstcorp.org/secure/Dashboard.jspa",
        "Source Code": "https://github.com/lsst-ts/ts_ofc",
    },
)
