{% set data= load_setup_py_data() %}
package:
  name: "ts-ofc"
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: 
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed .

test:
  requires:
    - ts-conda-build =0.4
    - scipy >=1.6
    - batoid >=0.5
    - galsim >=2.5
  source_files:
    - python
    - tests
    - pyproject.toml
  commands:
    - pytest -vs

requirements:
  host:
    - numpy {{ numpy }}
    - pip
    - python {{ python }}
    - setuptools {{ setuptools }}
    - setuptools_scm {{ setuptools_scm }}
  build:
    - numpy {{ numpy }}
    - python {{ python }}
    - setuptools {{ setuptools }}
    - setuptools_scm {{ setuptools_scm }}
    - ts-conda-build =0.4
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - scipy >=1.6
    - batoid >=0.5
    - galsim >=2.5
    - ruamel.yaml

